apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    component: shipping
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      component: shipping
      project: roboshop
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
    spec:
      containers:
      - name: shipping
        image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/shipping:TAG
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    component: shipping
    project: roboshop
spec:
  selector:
    component: shipping
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
