componentName: shipping
image:
  component: shipping
health:
  path: /health
  port: "8080"
configMap:
  enabled: true
  data:
    DB_HOST: "mysql"
    CART_ENDPOINT: "cart:80"
resources:
   limits:
     cpu: 1600m
     memory: 3600Mi
   requests:
     cpu: 1600m
     memory: 3600Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
