componentName: shipping
image:
  component: shipping
health:
  path: /health
  port: "8080"
configMap:
  enabled: true
  data:
    DB_HOST: "mysql"
    CART_ENDPOINT: "cart:80"
resources:
   limits:
     cpu: 2000m
     memory: 3600Mi
   requests:
     cpu: 2000m
     memory: 3600Mi

